

spring:
  application:
  name: Connect
  profiles:
    active: prod
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      host: localhost
      port: 27017
      database: CONNECTDB
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: imhamzase7en@gmail.com
    password: XXX XXX XXX XXX
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




#weather:
#  api:
#    key: e44f51fd9b1ce0fbd4f5bd9a1d81e057


server:
  port: 8080


logging:
  level:
    net:
      connect:
        Connect: DEBUG

# 1. ERROR
# 2. WARN
# 3. INFO
# 4. DEBUG
# 5. TRACE